[workspace]
members = [
	"tauri",
	"frontend"
]

[workspace.dependencies]
onlivfe_wrapper = { git = "https://github.com/onlivfe/core.git" }
# TODO: Move to onlivfe wrapper as re-export
onlivfe = { git = "https://github.com/onlivfe/core.git", default-features = false }
# TODO: Move to onlivfe wrapper as re-export as a feature
onlivfe_cache_store = { git = "https://github.com/onlivfe/core.git" }

# TODO: Move to onlivfe wrapper as re-exports
neos = "*"
chilloutvr = "*"
vrc = "*"

# Data mangling
serde = "1"
serde_json = "1"
