[application]

# App (Project) Name
name = "Tantalos"
asset_dir = "res"
default_platform = "desktop"


[web.app]

# HTML title tag content
title = "Tantalos"
watch_path = ["src", "res"]


# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []


[bundle]
identifier = "com.munally.tantalos"
publisher = "munally.com"
icons = ["./res/icons/icon.png"]
resources = ["./res/icons/icon.png"]
copyright =	"The onlivfe contributors"
short_description = "Onlivfe GUI"
long_description = "An onlivfe GUI to interact with social VR platforms"
