import { Icon } from "./icon.slint";
import { Globals } from "./globals.slint";
import { PredefinedThemes, Theme } from "theme.slint";
import { Palette } from "std-widgets.slint";

export component MainWindow inherits Window {
    background: Globals.theme.bg-root;
    default-font-family: "Jost*";
    default-font-size: 16px;

    
    preferred-width: 1280px;
    preferred-height: 720px;
    
    title: @tr("title" => "Tantalos - VR socials");
    icon: @image-url("../icons/icon.png");
    no-frame: false;

    property <ColorScheme> color-scheme: Globals.theme.color-scheme;
    changed color-scheme => { Palette.color-scheme = self.color-scheme; }
    init => { 
        Globals.theme = PredefinedThemes.dark;
        Palette.color-scheme = Globals.theme.color-scheme;
     }
}


export { PredefinedThemes, Globals }
