import { Palette } from "std-widgets.slint";


export struct Background  {
    color: brush,
    shadow: brush,
    border: brush
}

export struct Theme  {
    color-scheme: ColorScheme,
    name: string,
    bg-root: brush,
    bg-back: Background,
    bg-front: Background,

    // Colorful
    primary: color,
    secondary: color
}


export global PredefinedThemes  {
    out property<Theme> dark: {
        color-scheme: ColorScheme.dark,
        name: @tr("Default dark"),
        bg-root: rgba(0, 0, 0, 1),
        bg-back: {
            color: #140004,
            shadow: #140004,
            border: #140004
        },
        bg-front: {
            color: #140004,
            shadow: #140004,
            border: #140004
        },
        primary: #140004,
        secondary: #140004
    };
}
